export const DELIVERIES =
    [
        {
        id: 0,
        username:'Alice',
        category: 'Grocery',
        zipcode: 12345,
        matched: false,
        store: "Target",
        date: "4/08/20",
        shoppingList:[],
        createdAt: "2020/4/12",
    },
        {
        id: 1,
        username:'Bob',
        category: 'Grocery',
        zipcode: 12345,
        matched: false,
        store: "Target",
        date: "4/08/20",
        shoppingList:[],
        createdAt: "2020/4/12",
    },
        {
        id: 2,
        username:'Cathy',
        category: 'Grocery',
        zipcode: 12345,
        matched: false,
        store: "Target",
        date: "4/08/20"     ,
        shoppingList:[]   ,
        createdAt: "2020/4/12",
    },
        {
        id: 3,
        username:'Dora',
        category: 'Grocery',
        zipcode: 12345,
        matched: false,
        store: "Target",
        date: "4/08/20" ,    
        shoppingList:[],
        createdAt: "2020/4/12",
    }
];