export const REQUESTS =
    [
        {
        id: 0,
        buyerName:'Allison Z.',
        typeErrand: 'Grocery',
        shoppingList:[{item: "potato", quantity: 12},{item: "apple", quantity: 14}],
        zipcode: "12345",
        store: "Target",
        buyerDate: "2020/4/11",
        address1: "St. address1",
        address2: "#201 -23",
        city: "Santa Clara",
        numItems: 21,
        driverName: "Juan Luis",
        driverPhone: "6501234562",
        driverDate: "2020/4/11",
        note: "You can find my house by looking for a giant green trash bin",
        createdAt: "2020/4/12",
        thankyounote: "Thank you so much!"
    },
        {
        id: 1,
        buyerName:'Allison Z.',
        typeErrand: 'Grocery',
        shoppingList:[{item: "potato", quantity: 12},{item: "apple", quantity: 14}],
        zipcode: "12345",
        store: "Target",
        buyerDate: "2020/4/11",
        address1: "St. address1",
        address2: "#201 -23",
        city: "Santa Clara",
        numItems: 21,
        driverName: "Juan Luis",
        driverPhone: "6501234562",
        driverDate: "2020/4/11",
        note: "You can find my house by looking for a giant green trash bin",
        createdAt: "2020/4/12",
        thankyounote: "Thank you!",
        venmo: true,
        cash: true,

    },
        {
        id: 2,
        buyerName:'Allison Z.',
        typeErrand: 'Grocery',
        shoppingList:[{item: "potato", quantity: 12},{item: "apple", quantity: 14}],
        zipcode: "12345",
        store: "Target",
        buyerDate: "2020/4/11",
        address1: "St. address1",
        address2: "#201 -23",
        city: "Santa Clara",
        numItems: 21,
        driverName: "Juan Luis",
        driverPhone: "6501234562",
        driverDate: "2020/4/11",
        note: "You can find my house by looking for a giant green trash bin",
        createdAt: "2020/4/12",
    },
        {
        id: 3,
        buyerName:'Allison Z.',
        typeErrand: 'Grocery',
        shoppingList:[{item: "potato", quantity: 12},{item: "apple", quantity: 14}],
        zipcode: "12345",
        store: "Target",
        buyerDate: "2020/4/11",
        address1: "St. address1",
        address2: "#201 -23",
        city: "Santa Clara",
        numItems: 21,
        driverName: "Juan Luis",
        driverPhone: "6501234562",
        driverDate: "2020/4/11",
        note: "You can find my house by looking for a giant green trash bin",
        createdAt: "2020/4/12",

            }
    ];