export const ADD_REQEUST_POST = "ADD_REQEUST_POST";
export const OFFER_TO_DELIVER = "OFFER_TO_DELIVER";
export const FILTER_REQUESTS = "FILTER_REQUESTS";
export const SEND_THANKYOU_NOTE = "SEND_THANKYOU_NOTE";