export const ADD_REQEUST_POST = "ADD_REQEUST_POST";
export const OFFER_TO_DELIVER = "OFFER_TO_DELIVER";
export const FILTER_REQUESTS = "FILTER_REQUESTS";
export const SEND_THANKYOU_NOTE = "SEND_THANKYOU_NOTE";
export const SET_UNMATCHED_REQUESTS ="SET_UNMATCHED_REQUESTS";
export const SET_MY_DELIVERIES = "SET_MY_DELIVERIES";
export const SET_MY_REQUESTS = "SET_MY_REQUESTS";